apiVersion: v1
kind: Secret
metadata:
  name: kubecoin-secrets
  labels:
    app: kubecoin
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'postgres' | base64 = cG9zdGdyZXM=
  # echo -n 'password' | base64 = cGFzc3dvcmQ=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
